---
- hosts: "{{hostname}}"
  become: yes
  gather_facts: false
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
    - name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest="{{apt_file}}" owner=root group=root mode=644
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install Google Chrome
      apt: pkg=google-chrome-stable state=latest
